baseURL = 'https://xezpeleta.github.io/'
languageCode = 'eu-es'
title = 'Xabiren bloga'
theme = "urdazuri"

author = "Xabi Ezpeleta"
copyright = "Copyright Â© 2021, Xabier Ezpeleta"

[build]
  writeStats = true
